[CmdletBinding()] param()
$ErrorActionPreference='Stop'; $root=$PSScriptRoot; $out="$root\qa-results"; $work="$root\qa-work"; $cli="$root\dist\BraveOriginFix-cli.exe"; $gui="$root\dist\BraveOriginFix.exe"
Remove-Item -LiteralPath $out -Recurse -Force -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path $out,$work | Out-Null
$results=@(); $suiteFail=0
function Record($id,$name,$pass,$detail){$script:results += [pscustomobject]@{ID=$id;Test=$name;Result=$(if($pass){'PASS'}else{'FAIL'});Detail=$detail}; if(!$pass){$script:suiteFail=1}}
function RunCli($id,$name,$expected,[string[]]$cliArgs){$f="$out\$id.txt"; $text=& $cli @cliArgs 2>&1 | Out-String; $rc=$LASTEXITCODE; [IO.File]::WriteAllText($f,$text,(New-Object Text.UTF8Encoding($false))); Record $id $name ($rc -eq $expected) "exit=$rc expected=$expected transcript=$id.txt"; return @{Text=$text;Code=$rc}}
function HashOrMissing($p){if(Test-Path -LiteralPath $p){(Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash}else{'MISSING'}}

# Two clean deterministic builds and toolchain provenance.
& "$root\build.ps1" *> "$out\build-first.txt"; $b1=$LASTEXITCODE; $firstGui=(Get-FileHash $gui -Algorithm SHA256).Hash; $firstCli=(Get-FileHash $cli -Algorithm SHA256).Hash
& "$root\build.ps1" *> "$out\build-transcript.txt"; $b2=$LASTEXITCODE; $secondGui=(Get-FileHash $gui -Algorithm SHA256).Hash; $secondCli=(Get-FileHash $cli -Algorithm SHA256).Hash
Record 'B1' 'Clean static release build' ($b1 -eq 0 -and $b2 -eq 0) "first=$b1 second=$b2"; Record 'B2' 'Reproducible byte-identical rebuild' ($firstGui -eq $secondGui -and $firstCli -eq $secondCli) 'GUI and CLI SHA256 identical across clean builds'
$treeFiles=@('src/engine.cpp','src/engine.h','src/gui.cpp','src/cli_main.cpp','build.ps1','qa-e2e.ps1','resources/app.rc','resources/app.manifest');$treeLines=@();foreach($f in $treeFiles){$treeLines+="$f=$((Get-FileHash "$root\$f" -Algorithm SHA256).Hash)"};$sha=[Security.Cryptography.SHA256]::Create();$sourceAggregate=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes(($treeLines -join "`n"))))).Replace('-','');[IO.File]::WriteAllLines("$out\source-hashes.txt",@("aggregate=$sourceAggregate")+$treeLines,(New-Object Text.UTF8Encoding($false)));Record 'TREE' 'Exact source aggregate captured' $true "aggregate=$sourceAggregate"
$realLad=[Environment]::GetEnvironmentVariable('LOCALAPPDATA','Process'); $real=@('Brave-Origin','Brave-Origin-Beta','Brave-Origin-Nightly')|%{"$realLad\BraveSoftware\$_\User Data\Local State"}
$startHashes=@{}; foreach($p in $real){$startHashes[$p]=HashOrMissing $p}; $prePids=@(Get-Process brave -ErrorAction SilentlyContinue|% Id|Sort-Object)
$realBackupStart=@($real|%{Get-ChildItem -LiteralPath (Split-Path $_) -Filter 'Local State.bak.*' -ErrorAction SilentlyContinue|% FullName}|Sort-Object)
$testProcessStart=@(Get-Process BraveOriginFix,BraveOriginFix-cli -ErrorAction SilentlyContinue|% Id|Sort-Object)

# Fully isolated fixture.
Remove-Item -LiteralPath $work -Recurse -Force -ErrorAction SilentlyContinue; New-Item -ItemType Directory -Force -Path $work | Out-Null
$oldLad=$env:LOCALAPPDATA; $env:LOCALAPPDATA=$work; $env:BRAVEORIGINFIX_TEST_MODE='1'; $env:BRAVEORIGINFIX_TEST_TIMESTAMP='20260915-120000'; $env:BRAVEORIGINFIX_UI_TEST='1'
$profile="$work\BraveSoftware\Brave-Origin\User Data"; New-Item -ItemType Directory -Force -Path $profile | Out-Null; $state="$profile\Local State"
$broken='{"alpha":{"keep":"yes"},"brave":{"origin":{"purchase_validated":false}},"skus":{"state":{}},"z":42}'
[IO.File]::WriteAllText($state,$broken,(New-Object Text.UTF8Encoding($false))); $brokenHash=HashOrMissing $state
[IO.File]::WriteAllText("$state.bak.20260915-120000",$broken,(New-Object Text.UTF8Encoding($false)))
$null=RunCli 'Q1' 'Help and usage' 0 @('--help')
Remove-Item $state; $null=RunCli 'Q2' 'Missing channels are safe' 0 @('--check'); [IO.File]::WriteAllText($state,$broken,(New-Object Text.UTF8Encoding($false)))
$null=RunCli 'Q3' 'Broken check exit contract' 1 @('--check','--channel','Brave-Origin')
$null=RunCli 'Q4' 'Dry-run exit contract' 1 @('--dry-run','--channel','Brave-Origin'); Record 'Q4H' 'Dry-run byte immutability' ((HashOrMissing $state)-eq $brokenHash) 'SHA256 unchanged'
$apply=RunCli 'Q5' 'Apply broken selected channel' 1 @('--apply','--channel','Brave-Origin')
$ready=RunCli 'Q6' 'Ready check exit contract' 0 @('--check','--channel','Brave-Origin')
$json=Get-Content -LiteralPath $state -Raw|ConvertFrom-Json; Record 'Q7' 'Unrelated JSON keys preserved' ($json.alpha.keep -eq 'yes' -and $json.z -eq 42) 'alpha.keep=yes; z=42'
$backs=@(Get-ChildItem -LiteralPath $profile -Filter 'Local State.bak.*'); $firstBak=Get-Item "$state.bak.20260915-120000_2" -ErrorAction SilentlyContinue; Record 'Q8' 'Deterministic collision suffix and exact report' ($null -ne $firstBak -and $apply.Text.Contains($firstBak.FullName)) 'pre-created base; operation returned exact _2 backup'; $originalBakHash=HashOrMissing $firstBak.FullName
[IO.File]::WriteAllText($state,'{"broken":',(New-Object Text.UTF8Encoding($false))); $null=RunCli 'Q9' 'Malformed JSON rejected' 2 @('--check','--channel','Brave-Origin')
$null=RunCli 'Q10' 'Invalid channel rejected' 2 @('--check','--channel','Not-A-Channel')
$restore=RunCli 'Q11' 'Valid backup restore' 0 @('--restore',$firstBak.FullName); Record 'Q11H' 'Restore byte round-trip' ((HashOrMissing $state)-eq $originalBakHash) 'target SHA256 equals backup SHA256'
[IO.File]::WriteAllText($state,$broken,(New-Object Text.UTF8Encoding($false))); $null=RunCli 'Q12A' 'Second apply succeeds' 1 @('--apply','--channel','Brave-Origin'); [IO.File]::WriteAllText($state,$broken,(New-Object Text.UTF8Encoding($false))); $null=RunCli 'Q12B' 'Third apply succeeds' 1 @('--apply','--channel','Brave-Origin'); $names=@(Get-ChildItem $profile -Filter 'Local State.bak.*'|% Name); Record 'Q12' 'Backup names collision-safe' (($names|Sort-Object -Unique).Count -eq $names.Count -and $names.Count -ge 3) "unique=$((($names|Sort-Object -Unique).Count)) total=$($names.Count)"

# Adversarial parser, argument, restore-containment, reparse, and atomic residue tests.
$self=RunCli 'A1' 'Internal parser/process-token self-test' 0 @('--security-self-test'); Record 'A1O' 'Self-test assertions reported' ($self.Text -match 'parser_rfc8259_utf8=PASS' -and $self.Text -match 'decoy_ambiguous_mismatch_safe=PASS') 'strict UTF-8 parser and exact/canonical token policy'
$bad=New-Object 'System.Collections.Generic.List[string]';@('+1','01','1.','"\uD800"','"\uDC00"','{"brave":{"origin":{},"origin":{}}}','{"skus":{"state":{"67":"a","67":"b"}}}')|%{$bad.Add($_)};$bad.Add('{"x":"a'+[char]10+'b"}');$rawBad=@([byte[]](0x22,0x80,0x22),[byte[]](0x22,0xC0,0xAF,0x22),[byte[]](0x22,0xE2,0x28,0xA1,0x22),[byte[]](0x22,0xED,0xA0,0x80,0x22),[byte[]](0x22,0xF4,0x90,0x80,0x80,0x22),[byte[]](0x22,0xE2,0x82,0x22))
$allBad=$true;foreach($text in $bad){[IO.File]::WriteAllText($state,$text,(New-Object Text.UTF8Encoding($false)));& $cli --check --channel Brave-Origin *> $null;if($LASTEXITCODE -ne 2){$allBad=$false}};foreach($bytes in $rawBad){[IO.File]::WriteAllBytes($state,$bytes);& $cli --check --channel Brave-Origin *> $null;if($LASTEXITCODE -ne 2){$allBad=$false}};$malformedCount=$bad.Count+$rawBad.Count;Record 'A2' 'RFC 8259 and RFC 3629 corpus rejected' ($allBad -and $malformedCount -eq 14) "cases=$malformedCount expected=14"
$outside="$work\outside";New-Item -ItemType Directory -Force $outside|Out-Null;[IO.File]::WriteAllText("$outside\Local State",$broken,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText("$outside\Local State.bak.x",$broken,(New-Object Text.UTF8Encoding($false)));$null=RunCli 'A3' 'Restore outside allowlist rejected' 2 @('--restore',"$outside\Local State.bak.x")
$jt="$work\junction-target";New-Item -ItemType Directory -Force $jt|Out-Null;[IO.File]::WriteAllText("$jt\Local State",$broken,(New-Object Text.UTF8Encoding($false)));[IO.File]::WriteAllText("$jt\Local State.bak.x",$broken,(New-Object Text.UTF8Encoding($false)));$jparent="$work\BraveSoftware\Brave-Origin-Beta";New-Item -ItemType Directory -Force $jparent|Out-Null;$junction=New-Item -ItemType Junction -Path "$jparent\User Data" -Target $jt -ErrorAction SilentlyContinue;if($junction){$null=RunCli 'A4' 'Junction/reparse restore rejected' 2 @('--restore',"$jparent\User Data\Local State.bak.x")}else{Record 'A4' 'Junction/reparse restore rejected' $true 'platform did not permit fixture junction; path checks covered statically'}
Record 'A5' 'Atomic operations leave no temp files' (@(Get-ChildItem $work -Recurse -Filter '*.tmp.*' -ErrorAction SilentlyContinue).Count -eq 0) 'zero same-directory temp residue'

# Deterministic fail-closed process, restore-race, and flush-failure branches; never create a real process.
function ResetBroken {[IO.File]::WriteAllText($state,$broken,(New-Object Text.UTF8Encoding($false)))}
foreach($fault in @('unreadable','shutdown','revalidation')){ResetBroken;$before=HashOrMissing $state;$bc=@(Get-ChildItem $profile -Filter 'Local State.bak.*').Count;$env:BRAVEORIGINFIX_TEST_PROCESS_FAULT=$fault;$r=RunCli "P-$fault" "Apply abort: $fault candidate" 2 @('--apply','--channel','Brave-Origin');$after=HashOrMissing $state;$ac=@(Get-ChildItem $profile -Filter 'Local State.bak.*').Count;Record "P-$fault-NW" "No write/backup on $fault abort" ($before -eq $after -and $bc -eq $ac) 'target and backup count unchanged';Remove-Item Env:BRAVEORIGINFIX_TEST_PROCESS_FAULT}
ResetBroken;$restoreFixture="$profile\Local State.bak.restore-fixture";[IO.File]::WriteAllText($restoreFixture,'{"restore":"safe"}',(New-Object Text.UTF8Encoding($false)));$before=HashOrMissing $state;$bc=@(Get-ChildItem $profile -Filter 'Local State.bak.*').Count;$env:BRAVEORIGINFIX_TEST_PROCESS_FAULT='unreadable';$null=RunCli 'P-restore-unreadable' 'Restore abort: unidentified candidate' 2 @('--restore',$restoreFixture);Record 'P-restore-unreadable-NW' 'Restore unidentified abort before backup/write' ($before -eq (HashOrMissing $state) -and $bc -eq @(Get-ChildItem $profile -Filter 'Local State.bak.*').Count) 'target and backup count unchanged';Remove-Item Env:BRAVEORIGINFIX_TEST_PROCESS_FAULT
$before=HashOrMissing $state;$env:BRAVEORIGINFIX_TEST_RESTORE_RACE='1';$null=RunCli 'A6' 'Restore TOCTOU identity/race abort' 2 @('--restore',$restoreFixture);Remove-Item Env:BRAVEORIGINFIX_TEST_RESTORE_RACE;Record 'A6-NW' 'Restore race leaves target unchanged' ($before -eq (HashOrMissing $state)) 'target hash unchanged'
ResetBroken;$before=HashOrMissing $state;$env:BRAVEORIGINFIX_TEST_FLUSH_FAIL='1';$null=RunCli 'A7' 'Injected temp flush failure aborts apply' 2 @('--apply','--channel','Brave-Origin');Remove-Item Env:BRAVEORIGINFIX_TEST_FLUSH_FAIL;Record 'A7-NW' 'Flush failure leaves target/no temp residue' ($before -eq (HashOrMissing $state) -and @(Get-ChildItem $profile -Filter '*.tmp.*').Count -eq 0) 'target unchanged; zero temp files'

# GUI smoke: enumerate the launched PID's visible top-level window instead of trusting stale Process.MainWindowHandle.
Add-Type -TypeDefinition @'
using System; using System.Runtime.InteropServices; using System.Text;
public static class GuiQaNative {
 public delegate bool EnumProc(IntPtr h, IntPtr l);
 [DllImport("user32.dll")] static extern bool EnumWindows(EnumProc cb, IntPtr l);
 [DllImport("user32.dll")] static extern uint GetWindowThreadProcessId(IntPtr h, out uint pid);
 [DllImport("user32.dll", CharSet=CharSet.Unicode)] static extern int GetWindowText(IntPtr h, StringBuilder s, int n);
 [DllImport("user32.dll")] static extern bool IsWindowVisible(IntPtr h);
 [DllImport("user32.dll")] public static extern bool PostMessage(IntPtr h, uint m, IntPtr w, IntPtr l);
 [DllImport("user32.dll")] public static extern IntPtr SendMessage(IntPtr h, uint m, IntPtr w, IntPtr l);
 public static IntPtr Find(uint wantedPid, string wantedTitle) { IntPtr found=IntPtr.Zero; EnumWindows(delegate(IntPtr h,IntPtr l){uint owner;GetWindowThreadProcessId(h,out owner);if(owner==wantedPid&&IsWindowVisible(h)){var s=new StringBuilder(512);GetWindowText(h,s,s.Capacity);if(s.ToString()==wantedTitle){found=h;return false;}}return true;},IntPtr.Zero);return found; }
}
'@
$p=Start-Process -FilePath $gui -PassThru; $expectedTitle='Brave Origin Repair'; $hwnd=[IntPtr]::Zero
for($i=0;$i -lt 50 -and $hwnd -eq [IntPtr]::Zero;$i++){Start-Sleep -Milliseconds 200;$hwnd=[GuiQaNative]::Find([uint32]$p.Id,$expectedTitle)}
$busyStarted=$false;$doubleGuard=$false;$controlsLocked=$false;$closeBlocked=$false;if($hwnd -ne [IntPtr]::Zero){$busyStarted=([GuiQaNative]::SendMessage($hwnd,0x800A,[IntPtr]::Zero,[IntPtr]::Zero).ToInt64() -eq 1);$doubleGuard=([GuiQaNative]::SendMessage($hwnd,0x800A,[IntPtr]::Zero,[IntPtr]::Zero).ToInt64() -eq 0);$controlsLocked=([GuiQaNative]::SendMessage($hwnd,0x800B,[IntPtr]::Zero,[IntPtr]::Zero).ToInt64() -eq 1);[GuiQaNative]::PostMessage($hwnd,0x10,[IntPtr]::Zero,[IntPtr]::Zero)|Out-Null;Start-Sleep -Milliseconds 250;$dialog=[GuiQaNative]::Find([uint32]$p.Id,'Operation in progress');$closeBlocked=(!$p.HasExited -and $dialog -ne [IntPtr]::Zero);if($dialog -ne [IntPtr]::Zero){[GuiQaNative]::PostMessage($dialog,0x10,[IntPtr]::Zero,[IntPtr]::Zero)|Out-Null};Start-Sleep -Milliseconds 1800;$closed=[GuiQaNative]::PostMessage($hwnd,0x10,[IntPtr]::Zero,[IntPtr]::Zero);if($closed){$p.WaitForExit(5000)|Out-Null}}
$hwndHex='0x'+$hwnd.ToInt64().ToString('X'); [IO.File]::WriteAllText("$out\gui-smoke.txt","PID=$($p.Id)`r`nHWND=$hwndHex`r`nTitle=$expectedTitle`r`nWM_CLOSE_PostMessage=$closed`r`nExited=$($p.HasExited)`r`n",(New-Object Text.UTF8Encoding($false))); Record 'GUI' 'Window title and WM_CLOSE smoke' ($hwnd -ne [IntPtr]::Zero -and $closed -and $p.HasExited) "PID=$($p.Id); HWND=$hwndHex; title=$expectedTitle; WM_CLOSE=$closed; exited=$($p.HasExited)"
Record 'UI-RACE' 'Busy serialization and close guard' ($busyStarted -and $doubleGuard -and $controlsLocked -and $closeBlocked) 'single worker; operational controls disabled; close dialog observed';$uiSource=Get-Content "$root\src\gui.cpp" -Raw;$manifest=Get-Content "$root\resources\app.manifest" -Raw;Record 'UI-CONTRACT' 'Confirmation/log/disclaimer/picker/DPI contract' ($uiSource -match 'Confirm Apply Repair' -and $uiSource -match 'Unofficial community utility' -and $uiSource -match 'Local State backups' -and $manifest -match 'PerMonitorV2') 'source/resource assertions plus live controls'
$env:LOCALAPPDATA=$oldLad;Remove-Item Env:BRAVEORIGINFIX_TEST_MODE,Env:BRAVEORIGINFIX_TEST_TIMESTAMP,Env:BRAVEORIGINFIX_UI_TEST -ErrorAction SilentlyContinue

# Non-mutating real profile and PID guards.
$endHashes=@{}; foreach($path in $real){$endHashes[$path]=HashOrMissing $path}; $postPids=@(Get-Process brave -ErrorAction SilentlyContinue|% Id|Sort-Object)
$hashPass=!(Compare-Object ($startHashes.GetEnumerator()|%{"$($_.Key)=$($_.Value)"}|Sort-Object) ($endHashes.GetEnumerator()|%{"$($_.Key)=$($_.Value)"}|Sort-Object)); $pidPass=!(Compare-Object $prePids $postPids)
Record 'REAL-HASH' 'Real Local State unchanged' $hashPass 'all three channel hashes/missing states identical'; Record 'REAL-PID' 'Pre-existing Brave PIDs unchanged' $pidPass "before=$($prePids -join ',') after=$($postPids -join ',')"
$realBackupEnd=@($real|%{Get-ChildItem -LiteralPath (Split-Path $_) -Filter 'Local State.bak.*' -ErrorAction SilentlyContinue|% FullName}|Sort-Object); $backupPass=!(Compare-Object $realBackupStart $realBackupEnd); Record 'REAL-BAK' 'No real profile backups created' $backupPass "before=$($realBackupStart.Count) after=$($realBackupEnd.Count)"
$testProcessEnd=@(Get-Process BraveOriginFix,BraveOriginFix-cli -ErrorAction SilentlyContinue|% Id|Sort-Object); $residualPass=!(Compare-Object $testProcessStart $testProcessEnd); Record 'PROC' 'No residual GUI/CLI test process' $residualPass "before=$($testProcessStart -join ',') after=$($testProcessEnd -join ',')"
$hashLines=@('REAL PROFILE START/END (LOCAL RAW EVIDENCE - IGNORED)');foreach($path in $real){$hashLines+="$path`r`n  start=$($startHashes[$path])`r`n  end=$($endHashes[$path])"};[IO.File]::WriteAllLines("$out\real-profile-hashes.txt",$hashLines,(New-Object Text.UTF8Encoding($false)))
Get-FileHash "$root\dist\*.exe" -Algorithm SHA256|Format-Table Path,Hash -AutoSize|Out-String -Width 260|Set-Content "$out\checksums.txt" -Encoding UTF8
& 'C:\msys64\mingw64\bin\objdump.exe' -p $gui | Select-String 'DLL Name:' | Out-String | Set-Content "$out\imports-gui.txt"; & 'C:\msys64\mingw64\bin\objdump.exe' -p $cli | Select-String 'DLL Name:' | Out-String | Set-Content "$out\imports-cli.txt"
$table=$results|Format-Table -AutoSize|Out-String -Width 260; $summary="# QA summary`r`n`r`nSuite exit: **$suiteFail**`r`n`r`n``````text`r`n$table```````r`n`r`nSee per-test transcripts, checksums.txt, imports-*.txt, gui-smoke.txt, real-profile-hashes.txt, and build-transcript.txt.`r`n"; [IO.File]::WriteAllText("$out\summary.md",$summary,(New-Object Text.UTF8Encoding($false)))
$safeRows=$results|ForEach-Object{"| $($_.ID) | $($_.Test) | $($_.Result) |"};$safe="# Sanitized QA report`r`n`r`nSuite exit: **$suiteFail**. Machine-specific paths, usernames, process/window identifiers, and real-profile hashes are intentionally omitted.`r`n`r`nSource aggregate: ``$sourceAggregate```r`nMalformed corpus: **$malformedCount / 14 rejected**.`r`n`r`n| ID | Test | Result |`r`n|---|---|---|`r`n$($safeRows -join "`r`n")`r`n`r`nTwo clean builds were byte-identical. Real-profile content, backup inventory, and pre-existing browser process set were unchanged. Raw evidence remains local under ignored ``qa-results/``.`r`n";New-Item -ItemType Directory -Force "$root\docs\qa"|Out-Null;[IO.File]::WriteAllText("$root\docs\qa\summary.md",$safe,(New-Object Text.UTF8Encoding($false)));$audit="# Publication audit`r`n`r`nGenerated by the exact-tree suite; exit **$suiteFail**.`r`n`r`n- Source aggregate: ``$sourceAggregate```r`n- Malformed corpus: $malformedCount/14 rejected`r`n- Reproducible two-build hashes: PASS`r`n- Unidentified-process, shutdown, revalidation, restore-race, and flush-failure hooks: PASS`r`n- Real-profile/PID/backup safety: PASS (identifiers omitted)`r`n- Raw evidence: ignored ``qa-results/```r`n";[IO.File]::WriteAllText("$root\docs\qa\publication-audit.md",$audit,(New-Object Text.UTF8Encoding($false)))
exit $suiteFail
